### ISSUE TITLE
Suggestion: PreMiD

### ISSUE THREAD

**Issue by liaminventions** [MCMi460/3DS-RPC#13]
i think it would be a lot more accessible and easier to use this if this was in PreMiD.

**Comment by MCMi460** [comment]
I don't understand how this could be. Would I just make a pull request to PreMiD with the updates and all of that? That seems like something that I shouldn't mess with considering the nature of this project is not particularly related to PreMiD's goal.

**Comment by liaminventions** [comment]
Oh, sorry i thought that it was possible to submit a presence to the store. nevermind.

**Comment by MCMi460** [comment]
It may be! But I'm not so sure if I want to go down that path, considering I know about as much about PreMiD as I know about dolphin mating patterns. ... Bad comparison -- I know a lot about those.

**Comment by liaminventions** [comment]
well, it seems like they are written in TypeScript anyway...

[https://docs.premid.app/en/dev/presence#:~:text=Open%20the%20extension%20popup%20in,dist%20folder%20of%20your%20presence.]()

**Comment by MCMi460** [comment]
I'll consider learning Typescript, but it's a bit of a farcry for me to add this to PreMiD.
I just wish I had more time as of lately. School has been eating so much of it up that I haven't had the opportunity to work on this as of lately.
