### ISSUE TITLE
Site wont create profile

### ISSUE THREAD

**Issue by superman055** [MCMi460/3DS-RPC#16]
So i have gone through the steps to register my friend code with the site but it never activates the console or creates a profile and i cant even delete it to try again.

**Comment by MCMi460** [comment]
You have definitely added the bot as a friend first, correct?
Then could you check if you have a space at the end of your status message on your 3DS? As stated by the TERMS.md, a space at the end of the status message will prevent the bot from saving any data to create a profile -- but it should still be able to be added to your list of consoles and used for Discord.

**Comment by superman055** [comment]
Yeah i just updated my status message on 3ds and it still throws an error when i try and create a profile but adding the console works but still wont allow me to activate it or delete the console.

**Comment by MCMi460** [comment]
It won't let you?
Perhaps you're being ratelimited? Try waiting a minute and trying again, I suppose?

**Comment by MCMi460** [comment]
Also -- what's the error for adding your profile? Does it say "successfully added" but only errors when you click "view profile"?

**Comment by superman055** [comment]
Yeah it says successfully added but errors out when i click on view profile

**Comment by superman055** [comment]
And it worked sorry for taking up your time man

**Comment by MCMi460** [comment]
Oh, I'm just glad that it worked out!
