### ISSUE TITLE
Error 61 every time you open the app, even when the site is up

### ISSUE THREAD

**Issue by aidinjk** [MCMi460/3DS-RPC#17]
<img width="382" alt="Screenshot 2023-06-15 at 2 16 36 PM" src="https://github.com/MCMi460/3DS-RPC/assets/69284371/e5a6bdd0-4fe2-42bf-b574-456e057dec89">

It was working fine whenever I tried it the first time, now it just says this every time.

**Comment by MCMi460** [comment]
This has to do with connecting to Discord, I believe. Try closing and reopening Discord on your computer before starting 3DS-RPC, or, if that does not work, try restarting your computer and then opening Discord first.
3DS-RPC, as of the current state of the GUI app, can only boot if opened after Discord.

**Comment by MCMi460** [comment]
If you're still having problems after trying the solution that I've posted, please re-open this issue.
