### ISSUE TITLE
User profile screen shows "URL was not found", even after a few minutes.

### ISSUE THREAD

**Issue by jameslandon786** [MCMi460/3DS-RPC#18]
![image](https://github.com/MCMi460/3DS-RPC/assets/72671316/994a3f7f-8b54-4ab2-b64c-d214120f3d16)
![image](https://github.com/MCMi460/3DS-RPC/assets/72671316/e4741bde-23a8-412b-af71-56ded82c7ff3)

**Comment by MCMi460** [comment]
An extra note: You don't need the Desktop app anymore for the website to work.
