### ISSUE TITLE
When I go to Settings i get an Internal Server Error

### ISSUE THREAD

**Issue by Gauley123** [MCMi460/3DS-RPC#19]
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by MCMi460** [comment]
Ah, I believe I've found a way to replicate this.
This occurs whenever the route `/settings` or `/settings.html` (which redirects to `/settings`) receives an invalid user token.
I fixed the problem for `/consoles` by forcing a logout whenever an invalid token is passed, but `/settings` does not have this safeguard.
To be certain that this is the problem, could you please go to https://3dsrpc.com/consoles and see if that forces you to log out? Then, try logging back in and going to https://3dsrpc.com/settings -- this should now work.

**Comment by Gauley123** [comment]
Yep, it works now.
