### ISSUE TITLE
[Request] Add Pretendo support

### ISSUE THREAD

**Issue by Emerald-Fox** [MCMi460/3DS-RPC#23]
I want to be able to use this while using Pretendo but it says the bot's friend code is invalid (makes sense because different server), It'd be useful to add support for Pretendo users, plus the fact Nintendo is shutting down the official servers next year would require this addition.

**Comment by oogabooga5** [comment]
Yh, would like Pretendo support as well. Still using Nintendo's servers but when MK7 is done for Pretendo probably gonna switch over

**Comment by SiirRandall** [comment]
+1 for me for Pretendo support. I know this took a long time to work on. It's so sad Nintendo is shutting down the servers. I can only imagine what the work would be like to move over to another platform. I love the service so far. Thanks again for the hard work.

**Comment by KodaKai1508** [comment]
+1 for this! Especially with the Nintendo Network servers closing in a month, migration to Pretendo is going ot become a must.

**Comment by MCMi460** [comment]
Pretendo support/migration will occur late March and early April.

**Comment by Siiyar** [comment]
has this already been added, since Nintendo Network shut down

**Comment by Pinkietron** [comment]
It's being worked on

**Comment by Preloading** [comment]
Almost done adding pretendo support

**Comment by TheBrockReal** [comment]
> Almost done adding pretendo support

Doubt it

**Comment by Preloading** [comment]
> > Almost done adding pretendo support
> 
> Doubt it
 
What do you mean? The code that adds it is RIGHT HERE: https://github.com/MCMi460/3DS-RPC/pull/28

**Comment by Tulip-0333** [comment]
This a thing yet? If so, how do you access it?

**Comment by Preloading** [comment]
> This a thing yet? If so, how do you access it?

Everything is ready for the owner repo, but SOMEONE *cough* *cough* delta, has managed to procrastinate putting the code that adds Pretendo for over 100 days

**Comment by spotlightishere** [comment]
This is currently deployed in production - we'll make a proper announcement after more testing to ensure everything is working smoothly. Thank you so much for the issue!

**Comment by chasio2221** [comment]
The client doesn't support Pretendo.
