### ISSUE TITLE
[Request] Add Linux desktop client

### ISSUE THREAD

**Issue by oogabooga5** [MCMi460/3DS-RPC#24]
A Linux desktop client would be nice for Linux users like me who don't want to run things through Wine.

**Comment by HotaruBlaze** [comment]
Linux just runs the code directly, it does not actually need a dedicated build

**Comment by MCMi460** [comment]
You can install Python and run the [app.py](https://github.com/MCMi460/3DS-RPC/blob/main/client/app.py) manually. The desktop client is EoL and will likely not receive any more non-stability updates, including ports. It is still being supported as a fallback, however.
