### ISSUE TITLE
The 3DS-RPC site hasen't generated my profile even a day after registeration?

### ISSUE THREAD

**Issue by PF94** [MCMi460/3DS-RPC#27]
Note that the Discord part works for me.

![image](https://github.com/MCMi460/3DS-RPC/assets/45898787/3db4b9c2-f52e-4885-afc9-8a510caa928a)

However, I have registered my 3DS yesterday, yet the profile still hasn't showed up.

![image](https://github.com/MCMi460/3DS-RPC/assets/45898787/191b96cd-a4d4-4129-9006-90a57869ee20)

![image](https://github.com/MCMi460/3DS-RPC/assets/45898787/9a5acf7c-ae3a-433e-82f1-2490b779d4b7)

A Mii called "Tiffany" (not my name) should show up on the website, since that's from the 3DS I registered with. (yes, it's crusty)

![2024-01-08 17 39 57](https://github.com/MCMi460/3DS-RPC/assets/45898787/ac3afc01-0d21-4676-9a47-211bbfaf0c52)

**Comment by MCMi460** [comment]
Firstly, does your 3DS friends status message end with a space? If so, the bot will ignore your friend card when making profiles.

Secondly, if not, try following [this tutorial](https://discord.com/channels/1012066992817193001/1119348280581685559/1119375862018617368) in [my Discord server](https://discord.gg/pwFASr2NKx).

**Comment by PF94** [comment]
My 3DS profile doesn't have any status.
