### ISSUE TITLE
There Literally is no add to consoles button theres only a go to consoles button ._.

### ISSUE THREAD

**Issue by Chriclercrap** [MCMi460/3DS-RPC#33]
There Literally is no add to consoles button theres only a go to consoles button ._. had to say this twice so i can get help quicker.

**Comment by Chriclercrap** [comment]
nope
![Screenshot (246)](https://github.com/MCMi460/3DS-RPC/assets/111613893/0200a55a-25bc-4883-8171-805bf5429128)

**Comment by kassiesplatoon** [comment]
there’s the button, press “register friend code” so u and the bot can add eachother as friends on the 3ds and the bot can update the status on the website from there!

**Comment by Chriclercrap** [comment]
i added the bot on 3ds and it dosent show the status at all plus i wanted it to show on discord as well.

**Comment by kassiesplatoon** [comment]
1. the status takes a few minutes to show up
2. i’ve had issues with it showing up on my discord status too, i made my own issue about it
looks like we just have to wait for them to fix the discord one

**Comment by Chriclercrap** [comment]
Whole month and it’s still not fixed gg’s this thing is done for.

**Comment by Preloading** [comment]
You may need to re-add the profile. If it doesn't add after 10 minutes, try readding. I believe there's a timer that if it takes over 10 minutes, it removes it or something (Delta named everything poorly, so i couldn't tell)

**Comment by spotlightishere** [comment]
There have been quite a few improvements to 3DS-RPC since, so hopefully this has since been resolved. Please feel free to file a new issue if you continue to encounter issues!
