### ISSUE TITLE
the bot has added me back, but games do not show up on my status. 

### ISSUE THREAD

**Issue by driz64** [MCMi460/3DS-RPC#34]
![Consoles _ 3DS-RPC - Google Chrome 7_7_2024 8_47_17 PM](https://github.com/MCMi460/3DS-RPC/assets/129793258/2e6bf878-1d8f-4eba-8930-4517d34443fe)

i've tried to redo this like 3 times and waited for a while but idk, am I glitched?

**Comment by Chriclercrap** [comment]
same

**Comment by MeijiRestored** [comment]
its a bug, the bot doesnt update discord statuses right now for some reason

**Comment by driz64** [comment]
do you know when it will be fixed?

**Comment by Moshi6401** [comment]
I've had this same issue for several months, still doesn't work for me.

**Comment by MeijiRestored** [comment]
I managed to fix this problem but unlinking the app in discord settings "authorized applications" and linking again.

**Comment by driz64** [comment]
still does not work, i just tried that 3 times.

**Comment by driz64** [comment]
yeah i guess this doesn't work then ggs

**Comment by Chriclercrap** [comment]
Damn that’s a shame thanks for wasting
My time stupid assholes who made this piece of shit.

**Comment by Chriclercrap** [comment]
Sorry your right im just so mad at the fact that it’s been a long time and
it still doesn’t work.

**Comment by driz64** [comment]
well right now it's working somewhat, my mii and nn name isn't showing up but what I'm playing is showing so that's a step in the right direction. What I did is download the client of 3ds rpc and let it run and closed it. i quit the client and readded my console on the website and it is working.
