### ISSUE TITLE
Website - Pretendo friend code doesn't work

### ISSUE THREAD

**Issue by Natino64** [MCMi460/3DS-RPC#38]
When asked to add 3ds-rpc onto your 3DS friends list (pretendo option) the friend code is listed as 0000-0000-0000. I'm assuming this is a bug, as adding that friend code results in an error on 3ds.

This means we can't add 3ds-rpc to our pretendo friends list, meaning we can't have discord statuses for our 3ds games.

**Comment by Preloading** [comment]
Hello there! The app is still under maintenance. We are working our hardest to implement pretendo support for the first time on 3DS-RPC, but we have run into roadblocks. (we made a mistake during testing, that bricked pretendo for the 3dsrpc console that you friend. we are contacting a dev to get this fixed). We added the UI for pretendo ~3 hours ago, so we're working our hardest fix this. (probably should have put a notice on the website about this tbh, but i do not control it)

**Comment by Natino64** [comment]
Ah, awesome! Just seen the UI update to say Pretendo is temporarily disabeld too. Thanks for the heads up!

Super cool project, best of luck with it!

Out of curiosity, do you have any rough-rough idea of when Pretendo will be working? By end-of-year possibly or is it still an unknown?

Thanks again!

**Comment by Preloading** [comment]
> Ah, awesome! Just seen the UI update to say Pretendo is temporarily disabeld too. Thanks for the heads up!
> 
> Super cool project, best of luck with it!
> 
> Out of curiosity, do you have any rough-rough idea of when Pretendo will be working? By end-of-year possibly or is it still an unknown?
> 
> Thanks again!

We are trying to get it ready, we are just waiting for a response from a pretendo dev. Shouldn't be too long.

**Comment by SepticRedhead** [comment]
> > Ah, awesome! Just seen the UI update to say Pretendo is temporarily disabeld too. Thanks for the heads up!
> > 
> > Super cool project, best of luck with it!
> > 
> > Out of curiosity, do you have any rough-rough idea of when Pretendo will be working? By end-of-year possibly or is it still an unknown?
> > 
> > Thanks again!
> 
> We are trying to get it ready, we are just waiting for a response from a pretendo dev. Shouldn't be too long.

Was there anything solved for the issue that caused you to have to disable pretendo friend code temporarily

**Comment by spotlightishere** [comment]
This is now deployed in production - we'll make a proper announcement after more testing to ensure everything is working smoothly. Thank you so much for the issue!
