### ISSUE TITLE
3DS-RPC never register your 3DS FC

### ISSUE THREAD

**Issue by Getze56901** [MCMi460/3DS-RPC#44]
Hi.
I'm trying to register my Pretendo FC into 3DS-RPC, but there's a issue when i register, the FC will never add your console and consequently the bot never adds you either.

Here's a video from the issue

https://github.com/user-attachments/assets/183c5335-b4d2-44b8-a098-0f66ab74fbf2

**Comment by Preloading** [comment]
Very Strange, I've tried to reproduce this but was unsuccessful. Could you try friending a different friend code if you have one? Or you can also try friending on Nintendo Network instead of pretendo

**Comment by Getze56901** [comment]
> Very Strange, I've tried to reproduce this but was unsuccessful. Could you try friending a different friend code if you have one? Or you can also try friending on Nintendo Network instead of pretendo

I tried now register a friend FC with default method and it didn't work and my friend register my FC succesfully and it appears in my profile but still bugged because still not RPC and i cannot select favorite my 3DS User

heres my video with the mentioned bugs:

https://github.com/user-attachments/assets/d53c6f7a-e003-4e18-98fb-93278360aacb

And here's the video of my friend registering my Pretendo FC successfully:

https://github.com/user-attachments/assets/7f0a67ec-d492-4b36-94bf-8d1c1e2139fc

**Comment by Getze56901** [comment]
UPDATE: Before doing a few things with the website and my friend, i managed get my RPC sucessfully.
I think is weirdly bugged
