### ISSUE TITLE
I don’t think the bot is friends with me on 3DS

### ISSUE THREAD

**Issue by poopgoopboop123abc** [MCMi460/3DS-RPC#45]
So I put in the friend code for the Bot and put in my friend code on 3DSrpc but the Bot doesn’t appear on my friend list so I don’t think it’s working. I’ve been waiting and even turned my console off and on but it still doesn’t work

**Comment by Preloading** [comment]
Duplicate of #42

**Comment by spotlightishere** [comment]
Closing this in favor of the aforementioned issue. We definitely have some issues here - thank you for reporting!
