### ISSUE TITLE
Rich Presence keeps saying "Playing" even with game closed

### ISSUE THREAD

**Issue by DefeatOf13** [MCMi460/3DS-RPC#47]
My 3DS is currently turned off and idk why my Discord status says that i'm playing (same for the website). I tried to remove the bot from the friend list but the problem persists, any fixes?

![Screenshot 2024-12-25 224817](https://github.com/user-attachments/assets/45a4863e-40d9-4493-8f8d-e2ee8c5d871d)

**Comment by DefeatOf13** [comment]
It fixed by itself, I don't know what happened

**Comment by spotlightishere** [comment]
Unfortunately, sometimes the bot can get locked up while fetching game information - this is an issue we're aware of, but have not yet diagnosed. Glad to hear it's now working!
