### ISSUE TITLE
Friendcode not recognized

### ISSUE THREAD

**Issue by ISAKEM** [MCMi460/3DS-RPC#5]
I run client.py and what I end up with is "APIException: {'Error': 'friendCode not recognized\nHint: You may not have added the bot as a friend'}" altho I have added it so whats going on here?

**Comment by liaminventions** [comment]
same issue here...

**Comment by MCMi460** [comment]
I'm perplexed as to why this is happening, as over my local tests it worked just fine with your friendcode.
I'm wiping the server and restarting it in case I somehow set it up wrongly last time. Maybe sqlite3 isn't so liable as a database provider after all?
The nature of the problem seems to originate exclusively from the frontend being incapable of adding a new friendcode to the database. Restarting the frontend did not seem to change anything, either. At least, I don't believe it did, since it's been a fully twenty-four hours since I last tested things, and I'm not sure if I tested that, though it seems like something I'd test!

**Comment by liaminventions** [comment]
`Failed
b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n'`

**Comment by MCMi460** [comment]
I have blundered again!
[Line 92](https://github.com/MCMi460/3DS-RPC/blob/fd2f86e53476d54348a7796a653765e54d207f48/server/server.py#L92) errors this:
```
(sqlite3.IntegrityError) NOT NULL constraint failed: friends.jeuFavori
[SQL: INSERT INTO friends (friendCode, online, titleID, updID, lastAccessed, accountCreation, lastOnline) VALUES ([REDACTED])]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```
Solution will come in a moment, but the reason why I didn't pick up on this during testing must be with a different version of sqlite or just a natural difference between versions on different operating systems. I'm not sure, but clearly me from 2022 knew what he was doing, and I'm interrupted his workflow lmao; bdb8089c7093022c3af78b76fe42c43bc386f4bf/[`line 24 of that commit`](https://github.com/MCMi460/3DS-RPC/blob/bdb8089c7093022c3af78b76fe42c43bc386f4bf/server.py#L24)

**Comment by MCMi460** [comment]
> that throws `Failed b'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n'`

That means the frontend is offline. I should probably add something to clarify that to the user.

**Comment by liaminventions** [comment]
thats what i figured because of the html

**Comment by MCMi460** [comment]
Thank you both for exposing so many issues with my more recent code! I feel like an idiot for not realizing it lol
Now that I think of it, #5 should've stopped _all_ new user creations, but I feel like a user joined during that time period after commit c08ef3e6aa187258db5f9a67aa1ce7f790b49a8c, which doesn't make much sense at all. I guess just proof that my machinations have left the machine running at a state beyond my individual intelligence.

**Comment by MCMi460** [comment]
The server is now up – is it working now?

**Comment by liaminventions** [comment]
`Failed
{'Error': 'friendCode not recognized\nHint: You may not have added the bot as a friend'}`

I'll restart the console and see if that solves it...

**Comment by MCMi460** [comment]
Agh, you're right – still no dice.

**Comment by liaminventions** [comment]
ok

**Comment by MCMi460** [comment]
I see the issue. Awaiting another fix for leading zeroes (how did I not see all of these issues before??).

**Comment by MCMi460** [comment]
Okay, could you try now please?

**Comment by liaminventions** [comment]
we're in buisness!
![WIN_20230211_21_34_06_Pro](https://user-images.githubusercontent.com/33787286/218289753-49cabdbc-f6fb-40db-8bb0-e93a17b545b2.jpg)

**Comment by MCMi460** [comment]
Ayyy!

**Comment by liaminventions** [comment]
oh yeah... 
![ohyeah](https://user-images.githubusercontent.com/33787286/218289829-b42484e4-16ad-40df-9fc4-e4dc97ddb7dd.png)

**Comment by MCMi460** [comment]
Sweet!

**Comment by liaminventions** [comment]
Thanks so much for the help - keep up the good work...

**Comment by MCMi460** [comment]
I'll close this issue now – thank you two both for helping me so much today lol
Have a great day and enjoy using 3DS-RPC!

**Comment by liaminventions** [comment]
your welcome.

**Comment by Metallix-the-Metal-Sonic** [comment]
I have had a somewhat similar issue to liaminventions, except every time the application opens, it immediately closes down with the same error message. It doesn't seem that the RPC works with Pretendo, but idk how to wipe the data from it to redo the friendcode entry
