### ISSUE TITLE
an invalid friend code was passed

### ISSUE THREAD

**Issue by liaminventions** [MCMi460/3DS-RPC#6]
I can't seem to add my friend code. all I get is:
`Traceback (most recent call last):
  File "client.py", line 213, in <module>
    main()
  File "client.py", line 208, in main
    raise e
  File "client.py", line 204, in main
    client = Client(region, friendCode)
  File "client.py", line 34, in __init__
    friendCode = str(convertPrincipalIdtoFriendCode(convertFriendCodeToPrincipalId(friendCode))).zfill(12) # Friend Code check
  File "/home/waverider/3DS-RPC/client/../api/love.py", line 24, in convertFriendCodeToPrincipalId
    if not checkPrincipalIdValidity(checksumByte, principalId): raise FriendCodeValidityError('an invalid friend code was passed')
api.love.FriendCodeValidityError: an invalid friend code was passed`

**Comment by liaminventions** [comment]
I am 100% sure that the friend code is correct by the way.

**Comment by MCMi460** [comment]
Could you please send me your friend code (if not on Github, over the [support Discord server](https://discord.gg/pwFASr2NKx))?
I can't really help without a friend code to check against, but it's entirely possible that my formula is wrong somehow (though I've already fixed it once before; I don't see how it would be again). It's probably something to do with an oddity in the friend code (leading zeroes? I thought I fixed that...).

**Comment by liaminventions** [comment]
0233-4325-8378 is the code.

**Comment by MCMi460** [comment]
Ah, the cursed leading zero. That's probably the problem, just from a first glance, but I'll have to dive in a little bit deeper to fix it lol.

**Comment by liaminventions** [comment]
I commented out the line that errors out, and it goes to downloading, but then crashes with this message: 
`Traceback (most recent call last):
  File "C:\Users\Liam\Downloads\3DS-RPC\client\client.py", line 213, in <module>
    main()
  File "C:\Users\Liam\Downloads\3DS-RPC\client\client.py", line 210, in main
    client.background() # Start client background, but leave on main thread
  File "C:\Users\Liam\Downloads\3DS-RPC\client\client.py", line 171, in background
    self.login() # Create account if not yet existent
  File "C:\Users\Liam\Downloads\3DS-RPC\client\client.py", line 109, in login
    raise APIException(r['Exception'])
api.util.APIException: {'Error': 'this client is invalid'}`

**Comment by MCMi460** [comment]
Yup, leading zero in hexadecimal gets stripped!

**Comment by MCMi460** [comment]
> I commented out the line that errors out, and it goes to downloading, but then crashes with this message: `Traceback (most recent call last): File "C:\Users\Liam\Downloads\3DS-RPC\client\client.py", line 213, in <module> main() File "C:\Users\Liam\Downloads\3DS-RPC\client\client.py", line 210, in main client.background() # Start client background, but leave on main thread File "C:\Users\Liam\Downloads\3DS-RPC\client\client.py", line 171, in background self.login() # Create account if not yet existent File "C:\Users\Liam\Downloads\3DS-RPC\client\client.py", line 109, in login raise APIException(r['Exception']) api.util.APIException: {'Error': 'this client is invalid'}`

That's just because I updated the server like twenty minutes ago for a separate thing. I'll push your fix with the friendcode in just a second.

**Comment by liaminventions** [comment]
Ok

**Comment by MCMi460** [comment]
Okay, downloading the client from the main branch should work now!
Thank you so much for telling me about this error.
I tested for leading zeroes in friend codes, but yours had a leading zero in its hexadecimal, too! (`0x056f5ddb0a`)

**Comment by MCMi460** [comment]
Oh, excuse me, it'll take two minutes or so for the server to restart with the new changes.

**Comment by MCMi460** [comment]
Alright, all done.

**Comment by liaminventions** [comment]
oh, no now i got `Traceback (most recent call last):
  File "C:\Users\Liam\Documents\GitHub\3DS-RPC\client\client.py", line 8, in <module>
    from api import *
  File "C:\Users\Liam\Documents\GitHub\3DS-RPC\client\..\api\__init__.py", line 5, in <module>
    from .util import * # utility
  File "C:\Users\Liam\Documents\GitHub\3DS-RPC\client\..\api\util.py", line 7, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'`

**Comment by liaminventions** [comment]
I think i updated the code incorrectly

**Comment by liaminventions** [comment]
It seems to be able to get to the "enter friend code" part at 7ac4ba5

**Comment by PoorPocketsMcNewHold** [comment]
Welp. This happen to me too.
```python
Traceback (most recent call last):
  File "/home/pm/Documents/3DS-RPC/client/client.py", line 218, in <module>
    main()
  File "/home/pm/Documents/3DS-RPC/client/client.py", line 205, in main
    raise e
  File "/home/pm/Documents/3DS-RPC/client/client.py", line 201, in main
    client = Client(friendCode, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pm/Documents/3DS-RPC/client/client.py", line 40, in __init__
    friendCode = str(convertPrincipalIdtoFriendCode(convertFriendCodeToPrincipalId(friendCode))).zfill(12) # Friend Code check
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pm/Documents/3DS-RPC/client/../api/love.py", line 24, in convertFriendCodeToPrincipalId
    if not checkPrincipalIdValidity(checksumByte, principalId): raise FriendCodeValidityError('an invalid friend code was passed')
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api.love.FriendCodeValidityError: an invalid friend code was passed
```
With `4425-1804-5982`*Also tried without the -*
