### ISSUE TITLE
Readline Not Available For Windows

### ISSUE THREAD

**Issue by MCMi460** [MCMi460/3DS-RPC#7]
oh, no now i got `Traceback (most recent call last):
  File "C:\Users\Liam\Documents\GitHub\3DS-RPC\client\client.py", line 8, in <module>
    from api import *
  File "C:\Users\Liam\Documents\GitHub\3DS-RPC\client\..\api\__init__.py", line 5, in <module>
    from .util import * # utility
  File "C:\Users\Liam\Documents\GitHub\3DS-RPC\client\..\api\util.py", line 7, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'`

_Originally posted by @liaminventions in https://github.com/MCMi460/3DS-RPC/issues/6#issuecomment-1426914598_

**Comment by MCMi460** [comment]
Blunder after blunder for me today... probably should've gotten more sleep last night.
Anyways, `readline` is not a module available for Windows (as I should've known and noticed), so I'll just replace it with `pyreadline3` or some other alternative.

**Comment by liaminventions** [comment]
oh ok

**Comment by liaminventions** [comment]
so sorry about this...

**Comment by liaminventions** [comment]
Also, I can get it to work in WSL but that cant access discord (I already knew this - not an issue)

**Comment by MCMi460** [comment]
WSL is Unix-based, so `readline` is included in the default Python package, but Windows doesn't like doing what the cool kids are doing :/

**Comment by MCMi460** [comment]
Well, oddly enough, I can't actually test this on Windows since (for whatever reason) my console doesn't have a single issue with importing `readline` in the first place (I don't even know anymore, I'm too tired. Probably some Windows thing that I'm too Mac to understand), so please tell me if the new main branch version works for you.
You will have to reinstall the `requirements.txt`

**Comment by liaminventions** [comment]
Got it, but now It thinks I don't have the bot? `Failed
{'Error': 'friendCode not recognized\nHint: You may not have added the bot as a friend'}`

**Comment by liaminventions** [comment]
also I can't enter my friend code anymore

**Comment by MCMi460** [comment]
Issue-hopping time lol
#5 now!

**Comment by liaminventions** [comment]
so it all comes down to #5...

**Comment by MCMi460** [comment]
I'm seriously starting to reconsider my line of work.

**Comment by liaminventions** [comment]
nah, your doing great
