### ISSUE TITLE
Exceeding Rate Limit Abnormally

### ISSUE THREAD

**Issue by MCMi460** [MCMi460/3DS-RPC#8]
If left sitting, the client will exceed the rate-limit for no apparent reason.

**Comment by MCMi460** [comment]
According to the server's logs, this is only happening to some users. I'm still unaware of why as of yet.

**Comment by MCMi460** [comment]
I believe the reason why would be `flask_limiter.util.get_remote_address()` returning `127.0.0.1` (have not yet tested to prove), which means that all user-specific IP ratelimits get grouped together for all users using the service, therefore if there is more than one person using the app at any one time, then the rate limit barrier easily gets hit quickly.

**Comment by MCMi460** [comment]
Can confirm – all remote addresses lump to `127.0.0.1`.

**Comment by MCMi460** [comment]
An upgrade to `flask-limiter==3.1.0` did not work.

**Comment by MCMi460** [comment]
I've figured out the issue and a fix will be committed shortly. The server was, indeed, failing to receive the proper remote addresses of users due to some proxy thing that I pretty much died inside trying to work out, but a phone call and a minor alteration to my nginx file later and it's working now, so that's all that matters, I suppose.
I have been conscious for over sixteen hours now. This should be considered a crime.

**Comment by ItzSwirlz** [comment]
Still happening for me with 1.0

**Comment by sashimi-ash** [comment]
Right now, the problem happens again.

**Comment by Metallix-the-Metal-Sonic** [comment]
I am using version 1.1, yet it seems that I still have this error

**Comment by zararashigal** [comment]
@HotaruBlaze Why the downvotes? Are you going to fix it for us?

**Comment by HotaruBlaze** [comment]
@zararashigal This is a old issue from 2023 being bumped once a year for no good reason, It was already explained by Delta that it's highly likely a user issue. 

Bumping a closed issue with "me too" isn't useful, If your really having issues like this your better going into the discord and asking for help as the discord is more up to date about issues going on.

**Comment by zararashigal** [comment]
We want this to be fixed. I have this on a freshly jailbroken 3ds and new account. This isnt an user issue.

**Comment by MCMi460** [comment]
@zararashigal 
This thread is not for your particular issue.

Please open a new issue with a screenshot of your task manager confirming that you do not have several instances of the client open simultaneously.

Furthermore, support for the desktop client is deprecated, as far as I'm concerned, and it is highly recommended that you use the website version here: https://3dsrpc.com/

**Comment by zararashigal** [comment]
I am not using the desktop client.
In fact i have always been using the web ui.
I haven't tried it this year around however, so that's on me. I was just notified for the downvotes. xD 
i can try this again tommorow when i've got a lovely nights sleep!

**Comment by HotaruBlaze** [comment]
> I am not using the desktop client. In fact i have always been using the web ui.

The Initial reason for this issue being created was because of the desktop client giving a rate limited error. and as @MCMi460 said, that turned out to be a server issue that was fixed.

@Metallix-the-Metal-Sonic Reported using version 1.1 and still having the error, with no follow up or real info being provided.

So to reiterate,

1) This specific bug was a configuration mistake that was made in 2023 and was resolved.
2) I disliked these posts because they are irrelevant to the actual issue, and are effectively a "me too", with no info or way to attempt to help.
3) You have just said you are not using the desktop client and this issue was to do with the desktop client/

So please either open a new issue that clearly outlines what you’ve tried so far, includes screenshots of the errors you’re seeing, and provides enough detail for someone to help or join the Discord.

**Comment by zararashigal** [comment]
Your web ui doesn't work.

**Comment by zararashigal** [comment]
> > I am not using the desktop client. In fact i have always been using the web ui.
> 
> The Initial reason for this issue being created was because of the desktop client giving a rate limited error. and as [@MCMi460](https://github.com/MCMi460) said, that turned out to be a server issue that was fixed.
> 
> [@Metallix-the-Metal-Sonic](https://github.com/Metallix-the-Metal-Sonic) Reported using version 1.1 and still having the error, with no follow up or real info being provided.
> 
> So to reiterate,
> 
>     1. This specific bug was a configuration mistake that was made in 2023 and was resolved.
> 
>     2. I disliked these posts because they are irrelevant to the actual issue, and are effectively a "me too", with no info or way to attempt to help.
> 
>     3. You have just said you are not using the desktop client and this issue was to do with the desktop client/
> 
> 
> So please either open a new issue that clearly outlines what you’ve tried so far, includes screenshots of the errors you’re seeing, and provides enough detail for someone to help or join the Discord.

Fair.

**Comment by MCMi460** [comment]
> Are you going to fix it for us?

> We want this to be fixed.

> Your web ui doesn't work.

@zararashigal These comments are inappropriate and rude. I am going to block you from this organization.

Thank you for understanding.
